# Generated by Django 3.1.7 on 2021-03-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tagcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.CharField(max_length=255, verbose_name='Владелец отзыва')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта клиента')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема обращения')),
                ('message', models.TextField()),
            ],
        ),
    ]
