# Generated by Django 3.1.7 on 2021-03-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0003_customermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to='account.useraccount'),
        ),
    ]
