# Generated by Django 3.1.7 on 2021-03-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customermessage_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermessage',
            options={'verbose_name': 'Сообщение клиента', 'verbose_name_plural': 'Сообщения клиента'},
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='custom',
            field=models.CharField(max_length=255, verbose_name='Владелец обращения'),
        ),
    ]
