# Generated by Django 3.1.7 on 2021-03-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210322_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermessage',
            name='custom',
            field=models.CharField(max_length=255, verbose_name='Имя владельца обращения'),
        ),
    ]
