# Generated by Django 3.1.7 on 2021-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210326_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Категории'),
        ),
    ]
