# Generated by Django 3.1.7 on 2021-03-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210329_0258'),
        ('main', '0008_auto_20210326_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='account.useraccount')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='prod_photos'),
        ),
        migrations.DeleteModel(
            name='CustomerMessage',
        ),
    ]
