# Generated by Django 3.1.7 on 2021-03-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210329_0258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Отзыв клиента', 'verbose_name_plural': 'Отзывы клиентов'},
        ),
        migrations.AddField(
            model_name='customerreview',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
