# Generated by Django 3.1.7 on 2021-03-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210329_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='prod_photos'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
