# Generated by Django 3.1.7 on 2021-03-29 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_auto_20210329_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'ordering': ('pub_date',), 'verbose_name': 'Отзыв клиента', 'verbose_name_plural': 'Отзывы клиентов'},
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
